### PR TITLE
Rich biome works again; implement diffuse gen.

### LINKED ISSUE #1710: Rich biome settings for mines
**Description of the Bug**
Rich biome settings for mines don't work.

**To Reproduce**

1. Travel to mesa
2. Look at xray results

**Expected behavior**
Should have more ore and a higher density

**Analysis**
The white black list is broken.

**Additional context**
Left here so we do not forget about this bug.

### PR DESCRIPTION
**Pull request by liach**
**The Issue**
 - Close #1710
 - Also implemented diffuse gen with vanilla ore gen
 
**The Proposal**
 - Tweaked logic to make sure black white lists work.
 
**Possible Side Effects**
 - The white black list should be right this time as we have tests.
 
**Alternatives**

### CODE REVIEW

File: src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java [hunk 1]
```diff
@@ -213,7 +222,7 @@ public boolean isRichBiome(Biome biome) {
                 return level == WhiteBlackList.PermissionLevel.WHITELISTED;
 
             // FIXME this is wrong, it doesn't have to match all
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java]: Might want to remove the FIXME

File: src/main/java/mods/railcraft/common/util/misc/WhiteBlackList.java [hunk 2]
```diff
@@ -58,16 +61,16 @@ public boolean isWhitelistEnabled() {
     }
 
     public boolean permits(T entry) {
-        return (!whitelistEnabled || whitelist.contains(entry)) && !blacklist.contains(entry);
+        return (whitelistEnabled && whitelist.contains(entry)) || !blacklist.contains(entry);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/util/misc/WhiteBlackList.java]: The blacklist should have priority according to the documentation in the cfg files.

File: src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java [hunk 3]
```diff
@@ -213,7 +222,7 @@ public boolean isRichBiome(Biome biome) {
...
-            return BiomeDictionary.getTypes(biome).stream().allMatch(richBiomeTypes::permits);
+            return BiomeDictionary.getTypes(biome).stream().anyMatch(richBiomeTypes::permits);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java]: This whole thing is no good. If any type is blacklisted, it should not be allowed. This check only checks that there is a type that is allowed which is also not blacklisted.

For example, you could blacklist Forest, and whitelist Mountains. The documentation indicates that a Biome of type "Mountainous Forests" would be blacklisted because it has Forest as a type. But the current implementation allows it because it has Mountain as a type and mountain isn't Blacklisted, ignoring the fact that Forest is blacklisted.

A proper solution must first check if the biome list intersects the blacklist, and if not, then check if the biome list intersects the whitelist.

**Review by CovertJaguar — CHANGES_REQUESTED** [review]
Still not quite right.

File: src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java (hunk 3 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java]: Fixed.

File: src/main/java/mods/railcraft/common/util/misc/WhiteBlackList.java (hunk 2 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/util/misc/WhiteBlackList.java]: Resolved.

File: src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/worldgen/OreGeneratorFactory.java]: Deleted.

**Review by CovertJaguar — APPROVED** [review]
