### PR TITLE
Moved all recipes to init

### LINKED ISSUE #1610: [1.12.2] Can't remove anything from Railcraft via Crafttweaker
I tried to remove recipes from Railcraft but it don't work. It seems that Railcraft recipes can't be removed.
Here is a simple script. -> https://pastebin.com/WuEMQhp2

Both commands did not work. recipes.remove and recipes.removeByRecipeName.

Forge: 2796
Crafttweaker: 4.1.13
Railcraft: 12.0.0 Beta 2

See also: https://github.com/CraftTweaker/CraftTweaker/issues/691

### PR DESCRIPTION
**Pull request by liach**
**The Issue**
 - Close #1610.
 - Describe the problem if an issue doesn't exist. Be as clear as possible.
 
**The Proposal**
 - This is to bring crafttweaker compatibility.
 - I inserted a log message and now confirm all recipes have been moved to init.
 
**Possible Side Effects**
 - Should be fine as mods already finish all registry things during preinit.
 
**Alternatives**
 - Might consider asking ct author for what else to do.

P.S. Forgot to open a pull for this change a few days ago. :sweat:

### CODE REVIEW

File: src/main/java/mods/railcraft/common/blocks/aesthetics/glass/BlockStrengthGlass.java [hunk 1]
```diff
@@ -90,8 +90,15 @@ public void initializeDefinition() {
     }
 
     @Override
-    public void finalizeDefinition() {
-        IRailcraftBlock.super.finalizeDefinition();
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/blocks/aesthetics/glass/BlockStrengthGlass.java:94]: Removing this breaks the color handler.

**Review by CovertJaguar — CHANGES_REQUESTED** [review]

File: src/main/java/mods/railcraft/common/blocks/aesthetics/glass/BlockStrengthGlass.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/blocks/aesthetics/glass/BlockStrengthGlass.java:94]: This is not removed; as the implementation for this method is removed, `finalizeDefinition` now inherits the default implementation from `IRailcraftBlock`.

**Review by CovertJaguar — APPROVED** [review]
