### PR TITLE
Various worldspike fixes

### LINKED ISSUE #847: Attempting to complete pairing with an anchor/sentinel which no longer exists does not cause an error
This is probably a low priority bug, given that there are two workarounds, but I thought it worth posting anyway (and I didn't see an existing bug report).

Basically, if you're trying to pair an anchor with a sentinel, and you destroy the anchor/sentinel that you BEGAN the pairing process with, you cannot complete or cancel the pairing process. Once this occurs, you cannot begin pairing on a new anchor/sentinel\* (*see workarounds).

In my opinion, if you try to complete pairing on an anchor/sentinel which no longer exists, you should receive an error to the effect of "the pair's origin no longer exists," and pairing should be cancelled allowing you to start the pairing process again. 

Minecraft: 1.7.10
Forge: 10.13.4.1614
Railcraft: 9.12.2

Here's a video:
https://youtu.be/j62CTe4fJUk

Reproduction steps:
1. Place an anchor and a sentinel anywhere in the world
2. While holding a crowbar, right click the sentinel to begin pairing
3. Destroy the sentinel
4. While holding a crowbar, right click the anchor -- normally this would produce some kind of message, but if a sentinel doesn't exist at the sentinel's original set coordinates, nothing happens
5. Create another sentinel (at a different set of coordinates)
6. While holding a crowbar, right click the sentinel to begin pairing -- in this case, you receive no error message, and you have no way\* (see workarounds) to pair the new sentinel with the anchor

Workaround:
- Logout of the server, or end single player game. Log back in, and re-pair; OR
- Place an anchor/sentinel at the original set of coordinates, complete pairing (either by pairing or cancelling) and destroy the anchor/sentinel

### LINKED ISSUE #1258: Worldspike Point xrays
image

### PR DESCRIPTION
**Pull request by liach**
Fixes #1258
Fixes #847 - Always clean up when failing to pair. Now missing ones will
be said to be "invalid"
Also fixed localized name of worldspike points.

### CODE REVIEW

**Review by CovertJaguar — CHANGES_REQUESTED** [review]
There is Style settings file in extras. Use it.

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java [hunk 1]
```diff
@@ -84,20 +86,29 @@ public float getBlockHardness(IBlockState state, World worldIn, BlockPos pos) {
...
+                "ogo",
+                'g', "ingotGold",
+                'p', Items.ENDER_PEARL,
+                'o', new ItemStack(Blocks.OBSIDIAN));
         }
     }
+
+    @Override
+    public String getUnlocalizedName() {
+        return super.getUnlocalizedName() + ".name";
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: What is the point of this?

This is basically the same as getLocalizedName().

**Review by CovertJaguar — CHANGES_REQUESTED** [review]

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: In the localization file, the name of spike point has a .name following, so there is an issue in the message when pairing.

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: Its the message that need fixing, not this.

Comment (liach) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: This is wrong because it is not from tiles. Will change in localization files then.

**Comment by liach** [comment]
Everything else is fine right? Will fix tonight.

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java (hunk 1 above)
Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: What? no that's not right either.

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: We are talking about the pairing messages right?

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/BlockWorldspikePoint.java]: The localization files are supposed to have the ".name" suffix. getUnlocalizedName() returns the tag without the ".name" suffix. getLocalizedName() returns it with it.

Overriding getUnlocalizedName() is definitely the wrong solution for whatever you are trying to do.

**Review by CovertJaguar — APPROVED** [review]

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java [hunk 2]
```diff
@@ -165,13 +171,15 @@ public boolean setPoint(EntityPlayer player, WorldCoordinate coord) {
...
+                ChatPlugin.sendLocalizedChatFromServer(player, "gui.railcraft.worldspike.pair.fail.alignment", getLocalizationTag(),
+                        state.getBlock().getUnlocalizedName());
                 return false;
             }
 
             int max = getMaxPointChunks();
             if (Math.abs(xChunk - xPointChunk) >= max || Math.abs(zChunk - zPointChunk) >= max) {
-                ChatPlugin.sendLocalizedChatFromServer(player, "gui.railcraft.worldspike.pair.fail.distance", getLocalizationTag(), state.getBlock().getUnlocalizedName());
+                ChatPlugin.sendLocalizedChatFromServer(player, "gui.railcraft.worldspike.pair.fail.distance", getLocalizationTag(),
+                        state.getBlock().getUnlocalizedName());
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java]: Are these wrong too?

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java [hunk 3]
```diff
@@ -465,8 +492,9 @@ public NBTTagCompound writeToNBT(NBTTagCompound data) {
     public void readFromNBT(NBTTagCompound data) {
         super.readFromNBT(data);
 
-        if (needsFuel())
+        if (needsFuel()) {
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java]: Don't commit these style changes.

**Review by CovertJaguar — CHANGES_REQUESTED** [review]

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java (hunk 2 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java]: Just searched for usages in the block class, sorry.

File: src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java (hunk 3 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/blocks/machine/worldspike/TileWorldspike.java]: For this I probably need to remake the whole thing.

**Comment by liach** [comment]
@CovertJaguar Please review again.

**Review by CovertJaguar — APPROVED** [review]
