### PR TITLE
Fixes cascading world gen

### LINKED ISSUE #1474: [1.12.2] Cascading world gen
[18:32:39] [Server thread/WARN] [FML]: Railcraft loaded a new chunk [5, 3] in dimension 0 (overworld) while populating chunk [5, 1], causing cascading worldgen lag.
[18:32:39] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[18:32:39] [Server thread/WARN] [FML]: Railcraft loaded a new chunk [5, 5] in dimension 0 (overworld) while populating chunk [5, 3], causing cascading worldgen lag.
[18:32:39] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[18:32:39] [Server thread/WARN] [FML]: Railcraft loaded a new chunk [6, 6] in dimension 0 (overworld) while populating chunk [5, 5], causing cascading worldgen lag.
[18:32:39] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[18:32:39] [Server thread/WARN] [FML]: Railcraft loaded a new chunk [7, 7] in dimension 0 (overworld) while populating chunk [6, 6], causing cascading worldgen lag.
[18:32:39] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

### PR DESCRIPTION
**Pull request by liach**
**The Issue**
 - Fixes #1474
 
**The Proposal**
 - Updates block setting/detection code.
 - Adds a util method for convenient setting.
 
**Possible Side Effects**
 - Might change the position of generations.
 
**Alternatives**
None I can see yet.

### CODE REVIEW

File: src/main/java/mods/railcraft/common/worldgen/Generator.java [hunk 1]
```diff
@@ -39,7 +39,7 @@ public final void generate(OreGenEvent.Post event) {
 
     @Override
     public final void generate(Random rand, int chunkX, int chunkZ, World world, IChunkGenerator chunkGenerator, IChunkProvider chunkProvider) {
-        _generate(rand, new BlockPos((chunkX << 4), 0, (chunkZ << 4)), world);
+        _generate(rand, new BlockPos((chunkX << 4) + 8, 0, (chunkZ << 4) + 8), world);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/worldgen/Generator.java:42]: Does this not counter all your - 8 additions? 😕

Comment (liach) [reply src/main/java/mods/railcraft/common/worldgen/Generator.java:42]: I am just regulating them so that in that abstract generate method below, i pass in the center pos (+8)

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/worldgen/Generator.java:42]: Then was it the setBlock changes that actually fixed the problem?

Comment (liach) [reply src/main/java/mods/railcraft/common/worldgen/Generator.java:42]: No. This also modifies the block lookup range (both the lookup of old blocks and setting of new blocks cause problems)

Before, we had 2 separate issues:
1. Lookup of blocks goes to other chunks and causing cascading world gen
2. Setting of new blocks cause observer updates and loading of adjacent chunks if on chunk border

These two issues are fixed together here.
