### PR TITLE
Fix bore mining and bukkit logging

### LINKED ISSUE #1752: Tunnel bore doesn't use a "shovel" with BwM's HCPiles so only gets piles of dirt/gravel/sand
Minecraft: 1.12.2
Forge: 14.2.5.2815
Railcraft: 12.0.0-beta-5
Better with Mods: 1.12-2.3.20-1027 @primetoxinz
Better with Lib: 1.12-1.5

**Description of the Bug**
When using a Railcraft Tunnel Bore with Better with Mods installed (with HCPiles turned on `Makes soils drop 75% of their content if not broken with a shovel to incentivize the use of shovels`) the tunnel bore gets piles of dirt/sand/gravel instead of the actual block.

**To Reproduce**
Run Tunnel Bore with BwM installed with HCPiles turned on (default) and mine through dirt/grass/sand/gravel

**Expected behavior**
Tunnel Bore should mine with a "shovel" to get full block. Not sure which mod (Railcraft of Better with Mods) should fix this

**Screenshots & Video**

**Logs & Environment**
latest.log --> https://paste.dimdev.org/agemopewuw.md
 - Full log: 
 - Crash report (If available): 

**Additional context**
EDIT primetoxinz is on an indefinitive break from MC dev

### LINKED ISSUE #1753: Railcraft Tunnel bore can't "mine" "big" Dynamic Trees
Minecraft: 1.12.2
Forge: 14.2.5.2815
Railcraft: 12.0.0-beta-5
Dynamic Trees: 1.12.2-0.9.4

Not sure which mod can fix (not sure if this is "Out of scope" of DT @ferreusveritas )

**Description of the Bug**
When encountering a Dynamic Trees tree, the tunnel bore gets stuck (not sure if this has anything to do with some of its trees being wider than a block or not. I did have it get stuck with a tree directly in front center as a one that was planted on the block just outside of the 3x3 area. Dynamic trees only require the main stump to be mined btw.

**To Reproduce**
Install mods. Run Tunnel bore into a "big" Dynamic Trees tree.

**Expected behavior**
Would be nice if it could mine the tree (or at least stop using fuel).

**Screenshots & Video**
Big tree with roots

Big tree 1 pixel wider than block below 

**Logs & Environment**
latest.log -->https://paste.dimdev.org/tuxegukuti.md
 - Full log: 

**Additional context**

### LINKED ISSUE #1759: Crash with BUKKIT caused by NPE
https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/util/misc/Game.java#L69
here invokes `Game.log()` which will invoke `Game.log("default")`
https://github.com/Railcraft/Railcraft/blob/mc-1.12.2/src/main/java/mods/railcraft/common/util/misc/Game.java#L125
and here invokes `enabledCategories::contains` while `enabledCategories` is not initialized yet, and will throw NullPointerException.

I've done an experiment to proof that:

image

image

And in order to fix this, you just need to move the declaration before the static code block, or just simply initialize in the static code block.

Game Stack Trace: 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.ExceptionInInitializerError
	at mods.railcraft.common.modules.RailcraftModuleManager.loadModules(RailcraftModuleManager.java:55)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:623)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:166)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:599)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at mods.railcraft.common.util.misc.Game.log(Game.java:125)
	at mods.railcraft.common.util.misc.Game.log(Game.java:121)
	at mods.railcraft.common.util.misc.Game.<clinit>(Game.java:69)
	... 37 more
```

### PR DESCRIPTION
**Pull request by liach**
**The Issue**
 - Close #1752 
 - Close #1753 
 - Close #1759
 
**The Proposal**
 - Rework bore mining to simulate players more.
 - Tweak game class to have field ordered in front.
 
**Possible Side Effects**
 - Nothing significant.
 
**Alternatives**
 - Using system flag should be better than commenting out code on need.

Note: ic2 maven is down so the build may fail.

### CODE REVIEW

File: src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java [hunk 1]
```diff
@@ -873,9 +870,8 @@ protected boolean mineBlock(BlockPos targetPos, BlockRailBase.EnumRailDirection
                 }
             }
         }
-        WorldPlugin.setBlockToAir(world, targetPos);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: When does this happen now?

Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: It is handled in `WorldPlugin#playerRemoveBlock`, a method originally used by the destruction enchantment of the crowbar.

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: So before the drops are calculated? Isn't this a problem?

**Comment by liach** [comment]
not a problem. drops are handled in harvestdropevent

File: src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: block removal should not be bound with dropping... does cancelling drop event only in forge prevent block breaking?

File: src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java [hunk 2]
```diff
@@ -820,37 +820,34 @@ protected boolean mineBlock(BlockPos targetPos, BlockRailBase.EnumRailDirection
...
-            if (!InvTools.isEmpty(stack)) {
-                items.add(stack);
+            if (silk) {
+                ItemStack stack = HarvestPlugin.getSilkTouchDrop(targetState);
+                if (!InvTools.isEmpty(stack)) {
+                    items.add(stack);
+                }
+                // Use modifiable lists for events
+            } else {
+                targetState.getBlock().getDrops(items, world, targetPos, targetState, fortuneLevel);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java:844]: If the block is removed when this line is called, it could return the wrong drops yes? At the very least any tile entities are probably gone.

Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java:844]: It is the same code as the old one. https://github.com/Railcraft/Railcraft/pull/1760/files#diff-601fb497a36abaa013f7ec1a8fb43f9aL842 The indent was just changed, so you may think this is the "incorrect new code."

Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java:844]: Fixed.

File: src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: Restored.

File: src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java [hunk 3]
```diff
@@ -823,7 +823,10 @@ protected boolean mineBlock(BlockPos targetPos, BlockRailBase.EnumRailDirection
         EntityPlayerMP fakePlayer = CartTools.getFakePlayerWith(this, head);
 
         // Fires break event within; harvest handled separately
-        if (!WorldPlugin.playerRemoveBlock(world, targetPos, fakePlayer, false))
+        BlockEvent.BreakEvent breakEvent = new BlockEvent.BreakEvent(world, targetPos, targetState, CartTools.getCartOwnerEntity(this));
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: Are we not using the fake player here?

Comment (liach) [reply src/main/java/mods/railcraft/common/carts/EntityTunnelBore.java]: ah, missed that when i rollback the changes.
