### PR TITLE
Fix #1153

### LINKED ISSUE #1153: Bugs with trades
https://github.com/CovertJaguar/Railcraft/blob/mc-1.10.2/src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java#L52-L61

Currently the locomotive and the track kit trade does not work as intended. It does not show up in the trades.

### PR DESCRIPTION
**Pull request by liach**
Now villagers sell locomotives. I will adjust track kit trades, so this is work in progress.

### CODE REVIEW

**Comment by liach** [comment]
@CovertJaguar Done.

**Comment by liach** [comment]
Status?

File: src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java [hunk 1]
```diff
@@ -172,4 +171,26 @@ private int stackSize(Random rand, Offer offer) {
...
+            trackKits = TrackRegistry.TRACK_KIT.getVariants()
+                .values()
+                .stream()
+                .filter(kit -> kit.isEnabled() && kit.isVisible())
+                .collect(Collectors.toList());
+        }
+
+        @Override
+        public void modifyMerchantRecipeList(MerchantRecipeList recipeList, Random random) {
+            ItemStack stack = trackKits.get(random.nextInt(trackKits.size())).getTrackKitItem(2);
```
Comment (CovertJaguar) [inline src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java]: This will crash if trackKits.size() == 0, which might be possible if everything is disabled.

**Review by CovertJaguar — CHANGES_REQUESTED** [review]

File: src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java (hunk 1 above)
Comment (liach) [reply src/main/java/mods/railcraft/common/worldgen/VillagerTrades.java]: I believe in my coding ability on the web editor.

**Review by CovertJaguar — APPROVED** [review]

**Comment by liach** [comment]
I'll squash and merge.
