### PR TITLE
Fix furnace cart linking

### LINKED ISSUE #1037: Furnace carts not working in 10.0.1
Seems they behave like vanilla carts - they do the thing where they stop moving after rounding a few corners, and they can't be linked with other carts.

### PR DESCRIPTION
**Pull request by liach**
Fixes #1037

### CODE REVIEW

**Comment by CovertJaguar** [comment]
Why did you remove the fuel overflow protection?

File: src/main/java/mods/railcraft/common/carts/EntityCartFurnace.java [hunk 1]
```diff
@@ -64,20 +67,20 @@ public void killMinecart(DamageSource par1DamageSource) {
...
-                    fuel += burnTime;
-                    ReflectionHelper.setPrivateValue(EntityMinecartFurnace.class, this, fuel, 1);
-
-                    pushX = posX - player.posX;
-                    pushZ = posZ - player.posZ;
-                }
+        if (stack != null) {
+            int burnTime = FuelPlugin.getBurnTime(stack);
+
+            if (burnTime > 0 && fuel + burnTime <= 32000) {
```
Comment (liach) [inline src/main/java/mods/railcraft/common/carts/EntityCartFurnace.java:76]: @CovertJaguar This is the fuel overflow protection, I did not remove it :(

Comment (CovertJaguar) [reply src/main/java/mods/railcraft/common/carts/EntityCartFurnace.java:76]: Oh wait derp. My bad.
